name: Run CI checks

on: [pull_request]

jobs:
  test: <-- give our job an ID
    runs-on: ubuntu-latest <-- the image our job will run on
    name: Testing affected apps <-- the name that will appear on the Actions UI
    steps: <-- what steps it will perform
      - uses: actions/checkout@v1 <-- checkout whatever branch the PR is using
      - uses: bahmutov/npm-install@v1.4.5 <-- trigger an `npm install`
      - run: npm run nx test store <-- test the "store" project
      - run: npm run nx test api <-- test the "api" project